export const fakeDecks = [
  {
    name: "Deck 1",
    description: "Description 1",
    tags: ["Tag1", "Tag2"],
    words: [
      {
        word: "Word1",
        englishDefinition: "Definition1",
        exampleSentence: "Example1",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word2",
        englishDefinition: "Definition2",
        exampleSentence: "Example2",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 2",
    description: "Description 2",
    tags: ["Tag2", "Tag3"],
    words: [
      {
        word: "Word3",
        englishDefinition: "Definition3",
        exampleSentence: "Example3",
        wordType: "Adjective",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 3",
    description: "Description 3",
    tags: ["Tag4"],
    words: [],
  },
  {
    name: "Deck 4",
    description: "Description 4",
    tags: ["Tag5"],
    words: [
      {
        word: "Word4",
        englishDefinition: "Definition4",
        exampleSentence: "Example4",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  {
    name: "Deck 5",
    description: "Description 5",
    tags: ["Tag2", "Tag5"],
    words: [
      {
        word: "Word5",
        englishDefinition: "Definition5",
        exampleSentence: "Example5",
        wordType: "Verb",
        conjugation: "Irregular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
      {
        word: "Word6",
        englishDefinition: "Definition6",
        exampleSentence: "Example6",
        wordType: "Noun",
        conjugation: "Regular",
        correctCount: [],
        incorrectCount: [],
        lastCorrectDate: null,
        lastIncorrectDate: null,
      },
    ],
  },
  // Add more decks here
];
